[package]
name = "espim"
version = "0.3.1"
authors = ["M*C*O <mcofficer@gmx.de>"]
edition = "2018"

[dependencies]
git2 = "0.9.2"
clap = "2.33.0"
app_dirs = "1.2.1"
symlink = "0.1.0"
dirs = "2.0.2"
reqwest = "0.9.19"
runas = "0.1.4"
yaml-rust = "0.4"
